version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directories:
      - "/*"
    schedule:
      interval: "weekly"
    groups:
      docker-updates:
        update-types:
          - "patch"
          - "minor"
