matrix:
  include:
    - env: CLOUD=amazon
    - env: CLOUD=azure
    - env: CLOUD=google

services:
  - docker

script:
  - make build-$(printenv CLOUD)
  - make test-$(printenv CLOUD)

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
    docker login -u="existenz" -p="$DOCKER_PASSWORD";
    make push-$(printenv CLOUD);
    fi

notifications:
  webhooks:
    urls:
      - secure: "KuEjtQcPsG4IHmU63zD0J56SF6HP/XslgevQ5ASxT8lWyWGmYNYhCCrd/L8w1wjy5Se/K2jbaeTETJd5bDk9JMGnIdy5yEeCzkw3mwiQIVtcO/RE3Evle58/4Sc7l17egAZ3tRT1eRQws1F1kwxckptCOmWwqutnANV9bO0sDJbXxHAWyRsK3ZTH4liNuTswRkaNeAOMJsf77WryhFNN8Z6aZqGKATyLn98n96QvV3kDIoliykKuuHYD8wbfR4sRLOrPkwdvHW2Sf6T3irqnJ0BewbvTUNlFdColrtp+17La/RlWgTgla9zXIoIM0hBZlmBBY7f4BG3JNWahVUsY30KNHYuBJR5NNPpBuab4GVVTcCZeR+A3heiI78d0Vq/j9kGylTJJZ3g3FutPjnX2VtOrtRicWf99AwEk0Zt4WI62vAYwizwLhYZn9J/yLf42F3oObh71fzJSuip/eOCkpS7CVN+guFb4f+ahHZpJBghfqk7llaZ2F0ED72rgcxJ9nI6GYlDugirmnDhroNxthCoygHm/cxkFL7k6TjJXHCCkA4/KR/L8qS0EwvHbUHDn5YorGtGBGoFgXNH/f0WkAbJHn5RHAAZY8hw+w5GyoDhov16Kj3dtDnhe92a2skqhQLmRn9Fwhg/WM3Cuk2r2PNffy0jvz633HxKU1LIVV9w="
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
